### PR TITLE
CIN-01147: Field type icons added to Form labels

### PR DESCRIPTION
**Pull request by cinchy-yogeshjagtap**
- resolved comment for outline font awsome icon

### CODE REVIEW

**Comment by cinchy-m** [comment]
@cinchy-yogeshjagtap The boolean icon is not displaying properly - it should be on the far left. It's currently on the right of the field value (checkbox)

field icons

**Comment by cinchy-yogeshjagtap** [comment]
Hi @cinchy-m , I have resolved above comment and also made checkbox icon change

**Review by alvin-h — APPROVED** [review]

**Comment by alvin-h** [comment]
should this be pointed to 5.2.1?

**Comment by alvin-h** [comment]
or maybe poitned to 5.3?

**Comment by cinchy-m** [comment]
@alvin-h Thanks. Switched to `v5.2.1`.

**Comment by cinchy-m** [comment]
@cinchy-yogeshjagtap The calculated column icon is not displaying correctly. As discussed, this is because the "result type" (useful for/required to render the input type) is being used instead of the "data type" (needed to correctly display the icon).

**Comment by cinchy-m** [comment]
This PR is complete but we need to update the query for calculated columns to return the field "type", as opposed to the field's "result type".

**Pull request merged**
